spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?useSSL=false&serverTimezone=UTC&useEncoding=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html
server:
  servlet:
    session:
      timeout: 3600s
      #cookie:
        # http‐only: true   # httpOnly如果为true，那么浏览器脚本将无法访问cookie
        # secure: true      # secure如果为true，则cookie将仅通过HTTPS连接发送